# Generated by Django 3.0.2 on 2020-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0002_auto_20200909_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(blank=True, choices=[('gbe', 'Grid-based'), ('totme', 'Theater-of-the-Mind'), ('lbe', 'Lore-based')], max_length=5, null=True),
        ),
    ]
