# Generated by Django 3.0.2 on 2020-09-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0003_auto_20200919_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='max_level',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='min_level',
        ),
    ]
