# Generated by Django 3.0.2 on 2020-09-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0006_auto_20200926_0225'),
        ('Campaign', '0006_auto_20200926_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='in_universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='World.Universe'),
        ),
    ]
