# Generated by Django 3.0.2 on 2020-09-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0007_auto_20200928_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='entry',
            new_name='flavor_text',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='exit',
        ),
    ]
