# Generated by Django 3.0.2 on 2020-10-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dungeon', '0003_delete_passageway'),
        ('ItemList', '0009_itemlist_in_project'),
        ('World', '0008_auto_20200930_1914'),
        ('Campaign', '0008_auto_20200930_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('encounter_num', models.IntegerField(blank=True, null=True)),
                ('encounter_type', models.CharField(blank=True, choices=[('gbe', 'Grid-based'), ('totme', 'Theater-of-the-Mind'), ('lbe', 'Lore-based')], max_length=5, null=True)),
                ('dramatic_question', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('flavor_text', models.TextField(blank=True, max_length=2500, null=True)),
                ('in_dungeon_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dungeon.Room')),
                ('in_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='World.Location')),
                ('in_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Campaign.Quest')),
                ('involved_npcs', models.ManyToManyField(blank=True, to='World.NPC')),
            ],
            options={
                'ordering': ['encounter_num'],
            },
        ),
        migrations.CreateModel(
            name='QuestEncounterLoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('in_encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Campaign.QuestEncounter')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemList.Item')),
            ],
            options={
                'verbose_name_plural': 'Encounter Loot',
            },
        ),
    ]
