# Generated by Django 3.0.2 on 2020-10-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0009_questencounter_questencounterloot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questencounterloot',
            options={'verbose_name_plural': 'Quest Encounter Loot'},
        ),
        migrations.RenameField(
            model_name='questencounterloot',
            old_name='in_encounter',
            new_name='in_questencounter',
        ),
    ]
