# Generated by Django 3.0.2 on 2020-10-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0010_auto_20201002_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounterloot',
            name='in_encounter',
        ),
        migrations.RemoveField(
            model_name='encounterloot',
            name='name',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.DeleteModel(
            name='EncounterLoot',
        ),
    ]
