# Generated by Django 3.1.2 on 2020-10-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('Campaign', '0012_auto_20201007_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='in_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AlterField(
            model_name='questencounter',
            name='in_quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign.quest'),
        ),
        migrations.AlterField(
            model_name='questencounterloot',
            name='in_questencounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign.questencounter'),
        ),
    ]
