# Generated by Django 3.1.2 on 2020-10-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0013_auto_20201012_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='in_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campaign.chapter'),
        ),
    ]
