# Generated by Django 3.1.2 on 2020-10-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0014_auto_20201012_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_num']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='questencounterloot',
            order_with_respect_to='name',
        ),
    ]
