# Generated by Django 3.1.2 on 2020-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0015_auto_20201014_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questencounter',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
