# Generated by Django 3.1.2 on 2020-11-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0027_citydemographics_in_project'),
        ('Campaign', '0021_auto_20201116_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='in_universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='World.universe'),
        ),
    ]
