# Generated by Django 3.1.2 on 2020-12-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0028_auto_20201124_1539'),
        ('Campaign', '0024_auto_20201124_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='in_area',
        ),
        migrations.AddField(
            model_name='quest',
            name='in_areas',
            field=models.ManyToManyField(blank=True, to='World.Area'),
        ),
        migrations.RemoveField(
            model_name='quest',
            name='in_city',
        ),
        migrations.AddField(
            model_name='quest',
            name='in_city',
            field=models.ManyToManyField(blank=True, to='World.City'),
        ),
    ]
