# Generated by Django 3.0.2 on 2020-08-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ItemList', '0001_initial'),
        ('World', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='World.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('room_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('flavor_text', models.TextField(blank=True, max_length=2500, null=True)),
                ('exits', models.ManyToManyField(blank=True, to='Dungeon.Room')),
            ],
            options={
                'ordering': ['in_roomset', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Roomset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_dungeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dungeon.Dungeon')),
            ],
        ),
        migrations.CreateModel(
            name='RoomLoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('in_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dungeon.Room')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemList.Item')),
            ],
            options={
                'verbose_name_plural': 'Room Loot',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='in_roomset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dungeon.Roomset'),
        ),
        migrations.CreateModel(
            name='Passageway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('passageway_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('flavor_text', models.TextField(blank=True, max_length=1500, null=True)),
                ('in_dungeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dungeon.Dungeon')),
            ],
        ),
    ]
