# Generated by Django 3.0.2 on 2020-09-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0003_auto_20200921_1920'),
        ('Dungeon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeon',
            name='in_location',
        ),
        migrations.AddField(
            model_name='dungeon',
            name='in_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='World.Area'),
        ),
    ]
