# Generated by Django 3.0.2 on 2020-09-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dungeon', '0002_auto_20200923_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passageway',
        ),
    ]
