# Generated by Django 3.1.2 on 2020-10-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0012_auto_20201012_0103'),
        ('Dungeon', '0003_delete_passageway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='in_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.area'),
        ),
        migrations.AlterField(
            model_name='room',
            name='flavor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='in_roomset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dungeon.roomset'),
        ),
        migrations.AlterField(
            model_name='roomloot',
            name='in_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dungeon.room'),
        ),
        migrations.AlterField(
            model_name='roomset',
            name='in_dungeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dungeon.dungeon'),
        ),
    ]
