# Generated by Django 3.1.2 on 2020-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dungeon', '0005_dungeon_landscape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
