# Generated by Django 3.1.2 on 2020-11-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('Dungeon', '0006_auto_20201104_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='in_project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='landscape',
            field=models.URLField(blank=True, help_text='Provide a URL to an image file.', max_length=255, null=True),
        ),
    ]
