# Generated by Django 3.1.2 on 2020-11-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('Dungeon', '0007_auto_20201110_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomset',
            name='in_project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
            preserve_default=False,
        ),
    ]
