# Generated by Django 3.0.2 on 2020-08-31 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_type', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Pantheon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('background', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('alternative_names', models.CharField(blank=True, max_length=255, null=True)),
                ('alignment', models.CharField(choices=[('LG', 'Lawful/Good'), ('NG', 'Neutral/Good'), ('CG', 'Chaotic/Good'), ('LN', 'Lawful/Neutral'), ('N', 'True Neutral'), ('CN', 'Chaotic/Neutral'), ('LE', 'Lawful/Evil'), ('NE', 'Neutral/Evil'), ('CE', 'Chaotic/Evil')], max_length=2)),
                ('background', models.TextField(blank=True, max_length=2500, null=True)),
                ('cult', models.TextField(blank=True, max_length=2500, null=True)),
                ('symbols', models.TextField(blank=True, max_length=1500, null=True)),
                ('god_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pantheon.GodType')),
                ('in_pantheon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pantheon.Pantheon')),
            ],
        ),
    ]
