# Generated by Django 3.0.2 on 2020-09-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0001_initial'),
        ('Pantheon', '0002_auto_20200909_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantheon',
            name='in_universe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='World.Universe'),
            preserve_default=False,
        ),
    ]
