# Generated by Django 3.1.2 on 2020-10-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pantheon', '0003_pantheon_in_universe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='alignment',
            field=models.CharField(blank=True, choices=[('LG', 'Lawful/Good'), ('NG', 'Neutral/Good'), ('CG', 'Chaotic/Good'), ('LN', 'Lawful/Neutral'), ('N', 'True Neutral'), ('CN', 'Chaotic/Neutral'), ('LE', 'Lawful/Evil'), ('NE', 'Neutral/Evil'), ('CE', 'Chaotic/Evil')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='god',
            name='in_pantheon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pantheon.pantheon'),
        ),
    ]
