# Generated by Django 3.1.2 on 2020-10-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pantheon', '0004_auto_20201012_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='god',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pantheon',
            options={'ordering': ['name']},
        ),
    ]
