# Generated by Django 3.1.2 on 2020-11-10 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('Pantheon', '0005_auto_20201014_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantheon',
            name='in_project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
            preserve_default=False,
        ),
    ]
