# Generated by Django 3.1.2 on 2020-12-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pantheon', '0008_auto_20201124_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='god',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
