# Generated by Django 3.0.2 on 2020-09-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
