# Generated by Django 3.0.2 on 2020-09-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0002_city_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.CharField(max_length=10),
        ),
    ]
