# Generated by Django 3.0.2 on 2020-09-26 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('World', '0004_remove_location_dungeon_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='in_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Project'),
        ),
    ]
