# Generated by Django 3.0.2 on 2020-09-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('World', '0005_universe_in_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='portrait',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universe',
            name='in_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Project'),
        ),
    ]
