# Generated by Django 3.0.2 on 2020-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0006_auto_20200926_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='npc_type',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(max_length=255),
        ),
    ]
