# Generated by Django 3.0.2 on 2020-10-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0009_worldencounter_worldencounterloot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldencounterloot',
            options={'verbose_name_plural': 'World Encounter Loot'},
        ),
        migrations.RenameField(
            model_name='worldencounterloot',
            old_name='in_encounter',
            new_name='in_worldencounter',
        ),
    ]
