# Generated by Django 3.0.2 on 2020-10-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0010_auto_20201003_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='landscape',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='landscape',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='landscape',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='landscape',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
