# Generated by Django 3.1.2 on 2020-10-12 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('World', '0011_auto_20201003_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='flavor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='in_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.region'),
        ),
        migrations.AlterField(
            model_name='area',
            name='landscape',
            field=models.URLField(blank=True, help_text='Provide a URL to an image file. Preferably, to the actual file, and not a link to a search engine.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='flavor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='landscape',
            field=models.URLField(blank=True, help_text='Provide a URL to an image file. Preferably, to the actual file, and not a link to a search engine.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cityquarter',
            name='flavor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empire',
            name='in_universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.universe'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='alignment',
            field=models.CharField(blank=True, choices=[('LG', 'Lawful/Good'), ('NG', 'Neutral/Good'), ('CG', 'Chaotic/Good'), ('LN', 'Lawful/Neutral'), ('N', 'True Neutral'), ('CN', 'Chaotic/Neutral'), ('CE', 'Chaotic/Evil'), ('NE', 'Neutral/Evil'), ('LE', 'Lawful/Evil')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='flavor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='landscape',
            field=models.URLField(blank=True, help_text='URL to an image file. The better the resolution, the longer the loading time.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='locationloot',
            name='in_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.location'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='alignment',
            field=models.CharField(blank=True, choices=[('LG', 'Lawful/Good'), ('NG', 'Neutral/Good'), ('CG', 'Chaotic/Good'), ('LN', 'Lawful/Neutral'), ('N', 'True Neutral'), ('CN', 'Chaotic/Neutral'), ('LE', 'Lawful/Evil'), ('NE', 'Neutral/Evil'), ('CE', 'Chaotic/Evil')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='portrait',
            field=models.URLField(blank=True, help_text='Provide a URL to an image file. Preferably, to the actual file, and not a link to a search engine.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='biome',
            field=models.CharField(blank=True, choices=[('Dr', 'Dry'), ('Tr', 'Tropical'), ('Te', 'Temperate'), ('Co', 'Continental'), ('Po', 'Polar')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='landscape',
            field=models.URLField(blank=True, help_text='Provide a URL to an image file. Preferably, to the actual file, and not a link to a search engine.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='universe',
            name='in_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AlterField(
            model_name='worldencounter',
            name='flavor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worldencounterloot',
            name='in_worldencounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.worldencounter'),
        ),
    ]
