# Generated by Django 3.1.2 on 2020-10-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0012_auto_20201012_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='cityquarter',
            options={'ordering': ['name'], 'verbose_name_plural': 'City Quarters'},
        ),
        migrations.AlterModelOptions(
            name='empire',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='faction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='universe',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='locationloot',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='worldencounterloot',
            order_with_respect_to='name',
        ),
    ]
