# Generated by Django 3.1.2 on 2020-11-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0013_auto_20201014_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='universe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
