# Generated by Django 3.1.2 on 2020-11-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('World', '0026_worldencounterloot_in_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='citydemographics',
            name='in_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
    ]
