# Generated by Django 3.1.2 on 2020-12-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0028_auto_20201124_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='leader_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='World.faction'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='in_faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faction', to='World.faction'),
        ),
    ]
