# Generated by Django 3.1.2 on 2020-12-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0029_auto_20201230_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='leaders',
        ),
    ]
