# Generated by Django 3.0.2 on 2020-09-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemList', '0003_itemlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
