# Generated by Django 3.0.2 on 2020-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemList', '0005_auto_20200911_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
    ]
