# Generated by Django 3.1.2 on 2020-10-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemList', '0010_auto_20201012_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
