# Generated by Django 3.1.2 on 2020-11-06 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('ItemList', '0011_auto_20201014_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
            preserve_default=False,
        ),
    ]
