# Generated by Django 3.1.2 on 2020-11-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        ('ItemList', '0012_item_in_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='in_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
    ]
