# Generated by Django 3.0.2 on 2020-09-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='game_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
