# Generated by Django 3.1.2 on 2020-10-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='game_system',
            field=models.CharField(blank=True, help_text='(e.g., Dungeons & Dragons 5th Edition, Shadowrun 20th Anniversary, ...', max_length=255, null=True),
        ),
    ]
