# Generated by Django 3.1.2 on 2020-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theLodge', '0002_auto_20201201_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditemlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
