# Generated by Django 3.1.2 on 2020-12-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theLodge', '0003_auto_20201208_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareditemlist',
            name='description',
            field=models.TextField(),
        ),
    ]
