# Generated by Django 3.1.2 on 2020-12-19 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('World', '0028_auto_20201124_1539'),
        ('theLodge', '0004_auto_20201209_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedUniverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('game_system', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('shared_at', models.DateField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.universe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
