# Generated by Django 3.1.2 on 2020-12-28 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20201012_0103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theLodge', '0005_shareduniverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('game_system', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('shared_at', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
